"""create ece services

Revision ID: 356521117ff6
Revises: 
Create Date: 2026-08-13 12:46:28.701538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356521117ff6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ece_services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('provider_code', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('service_type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('suburb', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('minimum_age_months', sa.Integer(), nullable=False),
    sa.Column('maximum_age_months', sa.Integer(), nullable=False),
    sa.Column('licensed_places', sa.Integer(), nullable=True),
    sa.Column('accepts_20_hours_ece', sa.Boolean(), nullable=True),
    sa.Column('availability_status', sa.String(length=40), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('ero_report_url', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            availability_status IN (\n                'unknown',\n                'available',\n                'waitlist',\n                'check_availability'\n            )\n            ", name=op.f('ck_ece_services_availability_status_valid')),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name=op.f('ck_ece_services_latitude_valid_range')),
    sa.CheckConstraint('licensed_places IS NULL OR licensed_places > 0', name=op.f('ck_ece_services_licensed_places_positive')),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name=op.f('ck_ece_services_longitude_valid_range')),
    sa.CheckConstraint('maximum_age_months >= minimum_age_months', name=op.f('ck_ece_services_maximum_age_not_less_than_minimum')),
    sa.CheckConstraint('minimum_age_months >= 0', name=op.f('ck_ece_services_minimum_age_months_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ece_services')),
    sa.UniqueConstraint('provider_code', name=op.f('uq_ece_services_provider_code')),
    sa.UniqueConstraint('slug', name=op.f('uq_ece_services_slug')),
    schema='app'
    )
    op.create_index('ix_ece_services_availability', 'ece_services', ['is_active', 'availability_status'], unique=False, schema='app')
    op.create_index('ix_ece_services_discovery', 'ece_services', ['is_active', 'region', 'suburb', 'service_type'], unique=False, schema='app')
    op.create_index('ix_ece_services_name', 'ece_services', ['name'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ece_services_name', table_name='ece_services', schema='app')
    op.drop_index('ix_ece_services_discovery', table_name='ece_services', schema='app')
    op.drop_index('ix_ece_services_availability', table_name='ece_services', schema='app')
    op.drop_table('ece_services', schema='app')
    # ### end Alembic commands ###
